# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e8e8fcf594b554a28a27bafca2d416be065bcea33612758a814547fdf1d013122a9129dacfd5e01d5ee967d9d7548df5465abd2ef7bba2a397257ed4128a175

test:
  secret_key_base: 2419bf2dd1b3665ed1fca856573e174e03b089d531e76d0aa4ee96fcc033e3c07b2ec7262cd95241b3025d96627b1e4c1dfaf4545b5227963bbebc34c7cf9d4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
